---
title: "AI Agents"
format:
  html:
    toc: true
    embed-resources: true
---

- Architecture of AI agents used.

- Frameworks used (e.g., LangChain, LlamaIndex, Haystack).

- Types of agents (e.g., tool-using agents, autonomous agents, planning agents).

- How agents interact with external tools and APIs.

---

*Explain overall structure, graph and in memory*

## Supervisor Agent

## Data Gathering Agent

The Data Gathering Agent is an autonomous agent designed to collect both stock price and news data based on the tickers specified in the user's query. To achieve this, the agent leverages two tools: `gather_data()` and `data_to_vectorstore()`. Regardless of the user's request type, this agent is always invoked as a first step following specific instructions. First, it identifies the tickers mentioned in the query and compiles them into a list to be passed into the gather_data() tool. Then, it gathers the most up-to-date price and news data for the defined tickers. Finally, if new data has been successfully retrieved, the agent either creates a new vectorstore or updates an existing one, ensuring that the information is ready to be used by the next agents in the process: the *RAG Agent* and the *Data Engineering Agent*.

## RAG Agent

## Data Engineering Agent




<br>
<!-- Reference to next section -->
<div style="text-align: right; font-size: 14px;">
  <a href="5_model.html">Next Section: Models and Technologies Used</a>
</div>

---

### References:

${^1}$ 