project:
  type: website
  output-dir: ../docs

website:
  title: Gen AI for Developers
  navbar:
    left:
      - text: Home | About Me
        href: https://mazuckerberg.georgetown.domains/

  sidebar:
    title: "Content:"
    style: "docked"
    collapse-level: 1
    align: left
    contents:
      - text: Github | Code
        href: https://github.com/gu-dsan6725/spring-2025-final-project-project-group-1
      - text: Introduction
        href: 1_introduction.html

format:
  html:
    theme: minty
    css: styles.css
    toc: true