project:
  type: website
  output-dir: ../docs

website:
  title: GIS for Spatial Data Science
  navbar:
    left:
      - text: Home | About Me
        href: https://mazuckerberg.georgetown.domains/

  sidebar:
    title: "Content:"
    style: "docked"
    collapse-level: 1
    align: left
    contents:
      - text: Github | Code
        href: https://github.com/mazuckerberg-git/GIS_project.io/tree/main/code
      - text: Github | Data
        href: https://github.com/mazuckerberg-git/GIS_project.io/tree/main/data
      - text: Introduction
        href: introduction.html

format:
  html:
    theme: minty
    css: styles.css
    toc: true