project:
  type: website
  output-dir: ../docs

website:
  title: Gen AI for Developers
  navbar:
    left:
      - text: Home | About Me
        href: https://mazuckerberg.georgetown.domains/

  sidebar:
    title: "Content:"
    style: "docked"
    collapse-level: 1
    align: left
    contents:
      - text: Github | Code
        href: https://github.com/gu-dsan6725/spring-2025-final-project-project-group-1
      - text: Introduction
        href: 1_introduction.html
      - text: Data Sources
        href: 2_data.html
      - text: Retrieval-Augmented Generation
        href: 3_rag.html
      - text: AI Agents
        href: 4_agents.html
      - text: Models and Technologies Used
        href: 5_model.html
      - text: Tools and Frameworks
        href: 6_tools.html
      - text: Evaluation of Effectiveness
        href: 7_evaluations.html
      - text: Responsible AI Considerations
        href: 8_AI_considerations.html
      - text: Findings and Insights
        href: 9_findings.html
      - text: Conclusion
        href: 10_conclusion.html
      
format:
  html:
    theme: Flatly
    css: styles.css
    toc: true
    toc-title: Contents